apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort  # Change this to NodePort if using a local Kubernetes cluster
